### ISSUE TITLE
setup github action with eslint

### ISSUE THREAD

**Issue by Idrinth** [jaymehta002/cricquest#5]
create  the file `.github/workflows/eslint.yml` and paste the following content inside:
```yml
name: ESLINT
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: latest
          cache: 'npm'
          cache-dependency-path: |
            package-lock.json
      - run: npm ci
      - run: npm run lint
```
This will make sure you nwo when you messed up directly
